// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://olymyudvqnawyjtfzpti.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9seW15dWR2cW5hd3lqdGZ6cHRpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzM2NDgyMDMsImV4cCI6MjA4OTIyNDIwM30.c1qscRxsnlc5F18lPi7KZ4JkxMPvAzBqUvv--5Q8pzY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});